[package]
name = "nlp100-rust"
version = "0.1.0"
authors = ["Jun Ohtani <johtani@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
rand = "0.7.3"
flate2 = "1.0.14"
regex = "1.3.7"
